#!/usr/bin/env bash
# HTTP request with name of web-server
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chmod 777 /etc/nginx/
sudo chmod 777 /etc/nginx/nginx.conf
sed -i "/sendfile on;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart