#!/usr/bin/env bash
#Trap
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "pkill -f [100-process_and_pid_file]" SIGINT
while :
do
    echo "To infinity and beyond"
    sleep 2
done