#!/usr/bin/env bash
#This script print 10 times "Best school" position 9 "Hi"
FizzBuzz=100
i=1
while [ "$i" -le "$FizzBuzz" ]
do
    if ((i % 3 == 0 )) && ((i % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0 ))
    then
        echo "Fizz"
    elif ((i % 5 == 0 ))
    then
        echo "Buzz"
    else
    echo "$i"
    fi
    ((i += 1))
done