#!/usr/bin/env bash
#print 10 times "Best school" while loop
minutes=59
hours=12
i=0
j=1
while [ "$i" -le "$hours" ]
do
    echo "Hour: $i"
    ((j = 1))
    while [ "$j" -le "$minutes" ]
    do
    echo "$j"
    ((j += 1))
    done
    ((i += 1))
done