#!/usr/bin/env bash
#Change the localhost IP
new_localhost='localhost'
new_facebook='facebook.com'
sed -i "s/^127.*/127.0.0.2 ${new_localhost}/" /etc/hosts
sed -i "s/^157.*/8.8.8.8 ${new_facebook}/" /etc/hosts
